---
# This playbook contains common plays that will be run all nodes.

- name: Install python-apt, aptitude, and debconf-utils
  shell: apt-get update && apt-get -y install python-apt aptitude debconf-utils
- name: Do any package upgrades
  apt: upgrade=dist
- name: Set default locale to en_US.UTF-8
  debconf: name=locales question='locales/default_environment_locale' value=en_US.UTF-8 vtype='select'
- name: Generate locales
  debconf: name=locales question='locales/locales_to_be_generated'  value='en_US.UTF-8 UTF-8' vtype='multiselect'
- name: Set timezone area
  debconf: name=tzdata question='tzdata/Areas' value='Etc' vtype='select'
- name: Set timezone
  debconf: name=tzdata question='tzdata/Zones/Etc' value='UTC' vtype='select'
  notify:
  - restart rsyslog
  - restart cron
- name: Install required packages
  apt: pkg={{ item }} state=latest
  with_items:
     - most
     - zsh
     - vim
     - vim-scripts
     - git
     - subversion
     - tmux
     - multitail
     - mtr-tiny
     - curl
     - dnsutils
     - sudo
     - gnupg
     - traceroute
     - htop
     - haveged
     - python-pip
     - unbound
     - duplicity
     - python-boto
     - build-essential
     - vnstat
     - python-dev
     - ntp
- name: Remove exim4 and consolekit
  apt: pkg={{ item }} state=absent
  with_items:
     - exim4-daemon-light
     - consolekit
- name: Ensure haveged, unbound, ntp, and vnstat are started on boot
  service: name={{ item }} enabled=yes
  with_items:
     - haveged
     - unbound
     - vnstat
     - ntp
- name: use local unbound instance for DNS and Google Public DNS as backup
  copy: src=resolv.conf dest=/etc/resolv.conf
